try { throw new Error; } catch {}
try { 1; } catch (x) { 2; } finally { 3; }
